package com.oss.model;

import com.eova.model.User;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("dicts", "id", Dicts.class);
		arp.addMapping("massage", "id", Massage.class);
		arp.addMapping("news", "id", News.class);
		arp.addMapping("newactivity", "id", Newactivity.class);
		arp.addMapping("spot", "id", Spot.class);
		arp.addMapping("note", "id", Note.class);
		arp.addMapping("note_reply", "id", NoteReply.class);
		arp.addMapping("note_user_item", "id", NoteUserItem.class);
		arp.addMapping("strategy", "id", Strategy.class);
		arp.addMapping("strategy_reply", "id", StrategyReply.class);
		arp.addMapping("strategy_user_item", "id", StrategyUserItem.class);
		arp.addMapping("user", "id", User.class);
	}
}

