package com.oss.model;

import com.oss.model.base.BaseDicts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dicts extends BaseDicts<Dicts> {
	public static final Dicts dao = new Dicts().dao();
}
