package com.oss.model;

import com.oss.model.base.BaseMassage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Massage extends BaseMassage<Massage> {
	public static final Massage dao = new Massage().dao();

}
