package com.oss.model;

import com.oss.model.base.BaseNewactivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newactivity extends BaseNewactivity<Newactivity> {
	public static final Newactivity dao = new Newactivity().dao();
}
