package com.oss.model;

import com.oss.model.base.BaseNoteUserItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoteUserItem extends BaseNoteUserItem<NoteUserItem> {
	public static final NoteUserItem dao = new NoteUserItem().dao();
}