package com.oss.model;

import com.oss.model.base.BaseNote;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Note extends BaseNote<Note> {
	public static final Note dao = new Note().dao();
}
