package com.oss.model;

import com.oss.model.base.BaseNoteReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoteReply extends BaseNoteReply<NoteReply> {
	public static final NoteReply dao = new NoteReply().dao();
}
