package com.oss.model;

import com.oss.model.base.BaseSpot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Spot extends BaseSpot<Spot> {
	public static final Spot dao = new Spot().dao();
}