package com.oss.model;

import com.oss.model.base.BaseStrategyUserItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StrategyUserItem extends BaseStrategyUserItem<StrategyUserItem> {
	public static final StrategyUserItem dao = new StrategyUserItem().dao();
}
