package com.oss.model;

import com.oss.model.base.BaseStrategyReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StrategyReply extends BaseStrategyReply<StrategyReply> {
	public static final StrategyReply dao = new StrategyReply().dao();
}
