package com.oss.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStrategyReply<M extends BaseStrategyReply<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStrategyId(java.lang.Integer strategyId) {
		set("strategy_id", strategyId);
		return (M)this;
	}
	
	public java.lang.Integer getStrategyId() {
		return getInt("strategy_id");
	}

	public M setReplyUser(java.lang.Integer replyUser) {
		set("reply_user", replyUser);
		return (M)this;
	}
	
	public java.lang.Integer getReplyUser() {
		return getInt("reply_user");
	}

	public M setReplyUsername(java.lang.String replyUsername) {
		set("reply_username", replyUsername);
		return (M)this;
	}
	
	public java.lang.String getReplyUsername() {
		return getStr("reply_username");
	}

	public M setToReplyUser(java.lang.Integer toReplyUser) {
		set("to_reply_user", toReplyUser);
		return (M)this;
	}
	
	public java.lang.Integer getToReplyUser() {
		return getInt("to_reply_user");
	}

	public M setToReplyUsername(java.lang.String toReplyUsername) {
		set("to_reply_username", toReplyUsername);
		return (M)this;
	}
	
	public java.lang.String getToReplyUsername() {
		return getStr("to_reply_username");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setReplyTime(java.util.Date replyTime) {
		set("reply_time", replyTime);
		return (M)this;
	}
	
	public java.util.Date getReplyTime() {
		return get("reply_time");
	}

}
