package com.oss.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDicts<M extends BaseDicts<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setObject(java.lang.String object) {
		set("object", object);
		return (M)this;
	}
	
	public java.lang.String getObject() {
		return getStr("object");
	}

	public M setField(java.lang.String field) {
		set("field", field);
		return (M)this;
	}
	
	public java.lang.String getField() {
		return getStr("field");
	}

	public M setExt(java.lang.String ext) {
		set("ext", ext);
		return (M)this;
	}
	
	public java.lang.String getExt() {
		return getStr("ext");
	}

}
